const eventsData = [
  {
    "id": "event-1",
    "title": "Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách",
    "category": "1 Profile riêng cho lễ cưới ",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng 1 Profile riêng cho lễ cưới . MC Bích Ngân đã dẫn dắt thành công chương trình \"Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1349.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1350.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1351.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1352.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1353.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1354.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1355.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1356.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1357.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1358.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1359.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1360.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1367.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1368.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1369.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1370.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1373.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1374.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1375.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1376.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1676.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1680.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1681.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_1913.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lâm Thy & Quốc Đạt - Nesta Hội An - 300 khách/IMG_2772.HEIC"
    ]
  },
  {
    "id": "event-2",
    "title": "Lễ cưới Tyler&Thao - Venue_ Fusion Resort",
    "category": "1 Profile riêng cho lễ cưới ",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng 1 Profile riêng cho lễ cưới . MC Bích Ngân đã dẫn dắt thành công chương trình \"Lễ cưới Tyler&Thao - Venue_ Fusion Resort\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0484.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0491.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0810.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0811.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0812.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0813.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0814.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0815.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0816.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0817.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0821.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0822.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0823.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0824.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0825.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0830.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_0832.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_4240.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_4242.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_8918.webp",
      "./asset/1 Profile riêng cho lễ cưới /Lễ cưới Tyler&Thao - Venue_ Fusion Resort/IMG_8921.webp"
    ]
  },
  {
    "id": "event-3",
    "title": "Thế Thịnh& Thanh Thuý",
    "category": "1 Profile riêng cho lễ cưới ",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng 1 Profile riêng cho lễ cưới . MC Bích Ngân đã dẫn dắt thành công chương trình \"Thế Thịnh& Thanh Thuý\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2615.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2616.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2617.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2618.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2619.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2620.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2621.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2622.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2623.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2624.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2625.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2627.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2628.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2629.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2630.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2631.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2632.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2633.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2634.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2637.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2638.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2639.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2641.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2642.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2644.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2645.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2646.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2647.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2648.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2649.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2765.webp",
      "./asset/1 Profile riêng cho lễ cưới /Thế Thịnh& Thanh Thuý/IMG_2781.HEIC"
    ]
  },
  {
    "id": "event-4",
    "title": "Ảnh này k có ảnh lễ cưới ",
    "category": "1 Profile riêng cho lễ cưới ",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng 1 Profile riêng cho lễ cưới . MC Bích Ngân đã dẫn dắt thành công chương trình \"Ảnh này k có ảnh lễ cưới \", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_1946.HEIC",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2071.webp",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2072.webp",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2073.webp",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2074.webp",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2075.webp",
      "./asset/1 Profile riêng cho lễ cưới /Ảnh này k có ảnh lễ cưới /IMG_2078.HEIC"
    ]
  },
  {
    "id": "event-5",
    "title": "Bất Động Sản - mở bán New Town Diamond",
    "category": "Show dẫn tiếng việt",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show dẫn tiếng việt. MC Bích Ngân đã dẫn dắt thành công chương trình \"Bất Động Sản - mở bán New Town Diamond\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A1621.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A1877.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A1897.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A1898.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A1899.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2000.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2048.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2049.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2053.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2054.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2144.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2147.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2171.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2172.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2176.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2209.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2213.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/1S9A2214.webp",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/IMG_6495.HEIC",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/IMG_6496.HEIC",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/IMG_6499.HEIC",
      "./asset/Show dẫn tiếng việt/Bất Động Sản - mở bán New Town Diamond/IMG_6501.HEIC"
    ]
  },
  {
    "id": "event-6",
    "title": "ACV - Cảng Hàng Không Quốc Tế Đà Nẵng",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"ACV - Cảng Hàng Không Quốc Tế Đà Nẵng\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/ACV308.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0219.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0220.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0221.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0222.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0223.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0224.HEIC",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0236.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0237.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0238.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0239.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0241.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0242.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0244.HEIC",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0245.HEIC",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0411.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0412.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0413.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0414.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0415.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0416.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0417.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0418.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0419.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0420.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0421.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0422.webp",
      "./asset/Show tiếng anh/ACV - Cảng Hàng Không Quốc Tế Đà Nẵng/IMG_0423.webp"
    ]
  },
  {
    "id": "event-7",
    "title": "Good food ",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Good food \", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Good food /4X6A8315.webp",
      "./asset/Show tiếng anh/Good food /4X6A8380.webp",
      "./asset/Show tiếng anh/Good food /4X6A8386.webp",
      "./asset/Show tiếng anh/Good food /TTL01542.webp",
      "./asset/Show tiếng anh/Good food /TTL01599.webp",
      "./asset/Show tiếng anh/Good food /TTL01685.webp",
      "./asset/Show tiếng anh/Good food /TTL01704.webp",
      "./asset/Show tiếng anh/Good food /TTL01714.webp",
      "./asset/Show tiếng anh/Good food /TTL01721.webp",
      "./asset/Show tiếng anh/Good food /TTL01921.webp",
      "./asset/Show tiếng anh/Good food /TTL01940.webp",
      "./asset/Show tiếng anh/Good food /TTL02005.webp",
      "./asset/Show tiếng anh/Good food /TTL02142.webp",
      "./asset/Show tiếng anh/Good food /TTL02143.webp",
      "./asset/Show tiếng anh/Good food /TTL02150.webp",
      "./asset/Show tiếng anh/Good food /TTL02153.webp",
      "./asset/Show tiếng anh/Good food /TTL02157(1).webp",
      "./asset/Show tiếng anh/Good food /TTL02157.webp",
      "./asset/Show tiếng anh/Good food /TTL02655.webp",
      "./asset/Show tiếng anh/Good food /TTL02656.webp"
    ]
  },
  {
    "id": "event-8",
    "title": "Hội Nghị Khách Hàng TCL",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Hội Nghị Khách Hàng TCL\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2634.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2635.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2636.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2637.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2638.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2639.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2640.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2641.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2642.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2643.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2644.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2645.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2646.webp",
      "./asset/Show tiếng anh/Hội Nghị Khách Hàng TCL/IMG_2647.webp"
    ]
  },
  {
    "id": "event-9",
    "title": "Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C110 (1).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C1103.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C112.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C120.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C126.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C127.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C128.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C129.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C132.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C137(1).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C137.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C140.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C15.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C17(1).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C17.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C177.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C18.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C185.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/2301_Menarini_C210.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (1 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (121 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (124 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (137 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (218 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (221 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (222 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (223 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (224 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (227 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (76 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (79 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (82 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/COLOR EVENT (84 of 244).webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/HH003684.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0792.HEIC",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0793.HEIC",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0794.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0795.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0834.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0835.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0836.webp",
      "./asset/Show tiếng anh/Menarini - kỷ niệm 15 năm thành lập - Color Event - Viettravel/IMG_0837.webp"
    ]
  },
  {
    "id": "event-10",
    "title": "Panasonic",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Panasonic\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Panasonic/IMG_0488.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0489.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0490.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0491.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0495.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0496.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0497.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0498.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0499.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0500.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0501.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0504.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0505.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0506.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0507.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0508.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0509.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0510.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0511.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0512.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0513.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0514.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0515.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0517.webp",
      "./asset/Show tiếng anh/Panasonic/IMG_0518.webp"
    ]
  },
  {
    "id": "event-11",
    "title": "Song ngữ Anh Việt - FLG Viet Nam",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Song ngữ Anh Việt - FLG Viet Nam\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3177.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3188.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3190.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3191.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3192.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3193.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/IMG_3195.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7188.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7278.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7281.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7303.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7672.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7676.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7679.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7747.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7766.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7881.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7899.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7900.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7903.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_7904.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_8115.webp",
      "./asset/Show tiếng anh/Song ngữ Anh Việt - FLG Viet Nam/SAM_8122.webp"
    ]
  },
  {
    "id": "event-12",
    "title": "Yep của Lg electonic Viet Nam",
    "category": "Show tiếng anh",
    "brief": "Một trong những sự kiện nổi bật thuộc mảng Show tiếng anh. MC Bích Ngân đã dẫn dắt thành công chương trình \"Yep của Lg electonic Viet Nam\", mang lại những khoảnh khắc đáng nhớ và chuyên nghiệp.",
    "images": [
      "./asset/Show tiếng anh/Yep của Lg electonic Viet Nam/NCT04227.webp",
      "./asset/Show tiếng anh/Yep của Lg electonic Viet Nam/NCT05111.webp",
      "./asset/Show tiếng anh/Yep của Lg electonic Viet Nam/NCT05123.webp"
    ]
  }
];

// Export for use if needed in modules, though in vanilla JS script tag inclusion, it acts as a global variable.
window.EVENTS_DATA = eventsData;
